-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 18:30:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mensagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mensagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mensagem` DEFAULT CHARACTER SET utf8 ;
USE `mensagem` ;

-- -----------------------------------------------------
-- Table `mensagem`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensagem`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `loginUsuario` VARCHAR(15) NOT NULL,
  `senhaUsuario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensagem`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensagem`.`mensagem` (
  `idMensagem` INT(11) NOT NULL AUTO_INCREMENT,
  `conteudoMensagem` VARCHAR(500) NOT NULL,
  `idDestinatario` INT(11) NOT NULL,
  `idRemetente` INT(11) NOT NULL,
  `dataMensagem` DATETIME NOT NULL,
  `status` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idMensagem`),
  INDEX `fkidUsuario_idx` (`idDestinatario` ASC),
  INDEX `fkidRemetente_idx` (`idRemetente` ASC),
  CONSTRAINT `fkidDestinario`
    FOREIGN KEY (`idDestinatario`)
    REFERENCES `mensagem`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkidRemetente`
    FOREIGN KEY (`idRemetente`)
    REFERENCES `mensagem`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
